### ISSUE TITLE
Blackbox data import

### ISSUE THREAD

**Issue by Nikel9O** [ElvinC/gyroflow#3]
Hi,
I've just stumbled upon [this](https://github.com/atomgomba/orangebox) project. 
I Think it could be useful to extract gyro data from black-box logs. 

what is your blackbox_extract.py expected to output exactly? might give it a look in the next few days.

**Comment by ElvinC** [comment]
Hey,

The purpose of blackbox_extract.py is to take in a path to a .bbl file, and extract the timestamped gyro data. The exact format isn't that important since everything can be converted/scaled, but the format I've been using is an Nx4 numpy array, where each of the N rows consists of [time, gyroX,gyroY,gyroZ], where time is in seconds and rate in rad/s. Feel free to implement it if you want :)

Also, since orangebox and crisp (as suggested [here](https://github.com/ElvinC/gyroflow/issues/2)) are GPL licensed, the same has to be the case for this project for compatibility. I'll change it shortly.

Thanks

**Comment by Nikel9O** [comment]
Hi,
i've finally made a flight with my new (used) hero 6. i thought this might be intresting/useful to you:
![immagine](https://user-images.githubusercontent.com/57232709/94197999-dd635900-feb6-11ea-8908-10300a9d2020.png)
It's the shape of gopro gyro x data (extracted using your script) and blackbox gyro x data from the same flight.
they seem to be quite different

while z seems relatively similar:
![immagine](https://user-images.githubusercontent.com/57232709/94198410-8447f500-feb7-11ea-9bcd-0c02f85ea6b0.png)

**Comment by ElvinC** [comment]
That's very interesting! Thanks a lot. I believe the coordinate system used for the gopro data is oriented differently compared to the standard betaflight one. The spikes in the blue gopro datapoints in your first graph seem to correspond the betaflight data in the second graph, just reversed. You can try to match those up to see how close they are. From a glance they do seem rather similar, so fingers crossed that it's close enough to be useful. The camera uptilt means that there's a coupling of yaw and roll in the unprocessed data, so I guess looking at the pitch axis gives the most fair comparison between the data.

I'll also try to make some further progress in the image processing code this weekend.

**Comment by Nikel9O** [comment]
You're right! Seems that the data just needs to be rotated (gopro x):
![immagine](https://user-images.githubusercontent.com/57232709/94292034-b2cbdb80-ff5c-11ea-9f89-8e0f3671a153.png)

the scheme between gopro gpmf and betaflight seems to be:
x => -y
y =>  z
z => -x

this is y:
![immagine](https://user-images.githubusercontent.com/57232709/94293347-68e3f500-ff5e-11ea-9e84-dfd531d4c8ec.png)

and this is y accounting for a -25 degree rotation on the data (my camera angle):
![immagine](https://user-images.githubusercontent.com/57232709/94293133-1e627880-ff5e-11ea-850f-7b3162945a8f.png)

I'd say they're pretty close!

**Comment by ElvinC** [comment]
That's awesome and really encouraging. Nice work! Also, I think I'm getting close to having the gyro video synchronization stuff working.

**Comment by b020** [comment]
Woa. Really nice job. I am subscribed to this project because I am really interested to see it working and use it on my weekend hobby flights footages. Unfortunately I am out of time to help with data and coding, since I am working a lot lately, I would have to learn python(currently I am a java dev), and I have a new born baby at home that drains out almost every spare minute I have left (lol).

Greetings from Brazil.
Keep up the good work, guys.
