### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Erik6209** [ElvinC/gyroflow#55]
Hi, i keep getting a runtime error while trying to "apply settings and compute sync".

![errors](https://user-images.githubusercontent.com/85838881/121814113-b086ea00-cc6f-11eb-920d-0daaca494a04.PNG)
![errors_0](https://user-images.githubusercontent.com/85838881/121814114-b11f8080-cc6f-11eb-8a07-0ef60b2409a7.PNG)
![errors_1](https://user-images.githubusercontent.com/85838881/121814115-b11f8080-cc6f-11eb-9f26-de81707589f6.PNG)

does anyone know what i'm doing wrong ?

**Comment by ElvinC** [comment]
It seems like the blackbox parser used sometimes doesn't parse the logs correctly (maybe if it's slightly corrupted), even though the blackbox explorer works fine. You can open the log in the blackbox explorer, export a CSV file, and use that instead of the raw log. (In the dev version I've added an error message when that happens explaining what to do)

**Comment by Erik6209** [comment]
@ElvinC that worked for me, thank you !
Overall the video looks great stabilized, but in some moments it wobbles. Is that caused by unclean gyro-data ?

**Comment by ElvinC** [comment]
> Is that caused by unclean gyro-data

Could be that or the sync
